apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "gpu-exporter"
  namespace: "kube-system"
  labels:
    app.kubernetes.io/name: "gpu-exporter"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "gpu-exporter"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: &portStr ':8956'
        prometheus.io/path: 'metrics'
      labels:
        app.kubernetes.io/name: "gpu-exporter"
      name: "gpu-exporter"
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: eagle-nest-registry-key
      containers:
        - image: "192.168.1.76:8099/evtrain/cvmart-gpu-exporter:v1"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: "EXPORTER_LISTEN"
              value: ":8956"
            - name: "EXPORTER_KUBERNETES"
              value: "true"
            - name: "NVIDIA_VISIBLE_DEVICES"
              value: "all"
          name: "gpu-exporter"
          ports:
            - name: "metrics"
              containerPort: &portInt 8956
              hostPort: *portInt
          volumeMounts:
            - mountPath: /host
              name: host-path
              readOnly: true
      volumes:
        - name: host-path
          hostPath:
            path: /
---

kind: Service
apiVersion: v1
metadata:
  name: "gpu-exporter"
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: "gpu-exporter"
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    app.kubernetes.io/name: "gpu-exporter"
    app.kubernetes.io/version: "1.0.0"
  ports:
    - name: "metrics"
      port: 8956
  type: NodePort
